/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package museo;

import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Artista;
import model.GestorBD;
import model.Obra;

/**
 *
 * @author matias
 */
public class AgregarObraa extends javax.swing.JFrame {

    ArrayList<Artista> list = new ArrayList<Artista>();
    GestorBD g = new GestorBD();
    Obra listo = new Obra();

    public AgregarObraa() {
        initComponents();
        cargarCombo();
        btnModificar.setVisible(false);
        btnVolver1.setVisible(false);
    }

    public AgregarObraa(Obra o1) {
        initComponents();
        cargarCombo();
        listo = o1;
        cargartxt();
        btnAgregar.setVisible(false);
        btnVolver.setVisible(false);
        btnModificar.setVisible(true);
        btnVolver1.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblArtista = new javax.swing.JLabel();
        lblAncho = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblValuacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblIngreso = new javax.swing.JLabel();
        cboArtista = new javax.swing.JComboBox<>();
        cboDescripcion = new javax.swing.JComboBox<>();
        txtAlto = new javax.swing.JTextField();
        txtIngreso = new javax.swing.JTextField();
        txtObra = new javax.swing.JTextField();
        txtAncho = new javax.swing.JTextField();
        txtValuacion = new javax.swing.JTextField();
        cboGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblAncho1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phto.setBackground(new java.awt.Color(0, 0, 0));
        phto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paint.jpg"))); // NOI18N
        phto.setAlignmentY(0.0F);
        getContentPane().add(phto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        lblArtista.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblArtista.setForeground(new java.awt.Color(255, 255, 255));
        lblArtista.setText("Artista:");

        lblAncho.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblAncho.setForeground(new java.awt.Color(255, 255, 255));
        lblAncho.setText("Ancho");

        lblGenero.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Genero");

        lblValuacion.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblValuacion.setForeground(new java.awt.Color(255, 255, 255));
        lblValuacion.setText("Valuacion");

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Obra");

        lblDescripcion.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripcion");

        lblIngreso.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblIngreso.setForeground(new java.awt.Color(255, 255, 255));
        lblIngreso.setText("Ingreso");

        cboArtista.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cboArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboDescripcion.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cboDescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo", "Regular" }));

        txtAlto.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtAlto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltoKeyTyped(evt);
            }
        });

        txtIngreso.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresoKeyTyped(evt);
            }
        });

        txtObra.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObraActionPerformed(evt);
            }
        });
        txtObra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObraKeyTyped(evt);
            }
        });

        txtAncho.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtAncho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnchoKeyTyped(evt);
            }
        });

        txtValuacion.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        txtValuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValuacionActionPerformed(evt);
            }
        });
        txtValuacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValuacionKeyTyped(evt);
            }
        });

        cboGenero.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surrealismo", "Cubismo", "Arte Pop", "Arte Abstracto", "Impresionismo", "Expresionismo", "Hiperrealismo", "Realismo" }));

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Obra");

        lblAncho1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        lblAncho1.setForeground(new java.awt.Color(255, 255, 255));
        lblAncho1.setText("Alto");

        btnAgregar.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(303, 233));
        btnAgregar.setMinimumSize(new java.awt.Dimension(303, 233));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setMaximumSize(new java.awt.Dimension(303, 233));
        btnVolver.setMinimumSize(new java.awt.Dimension(303, 233));
        btnVolver.setPreferredSize(new java.awt.Dimension(77, 25));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(303, 233));
        btnModificar.setMinimumSize(new java.awt.Dimension(303, 233));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnVolver1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnVolver1.setText("Volver");
        btnVolver1.setMaximumSize(new java.awt.Dimension(303, 233));
        btnVolver1.setMinimumSize(new java.awt.Dimension(303, 233));
        btnVolver1.setPreferredSize(new java.awt.Dimension(77, 25));
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblArtista)
                            .addComponent(lblGenero)
                            .addComponent(lblValuacion)
                            .addComponent(lblIngreso)
                            .addComponent(lblAncho)
                            .addComponent(jLabel2)
                            .addComponent(lblDescripcion)
                            .addComponent(lblAncho1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIngreso)
                            .addComponent(txtAncho)
                            .addComponent(txtAlto)
                            .addComponent(txtValuacion)
                            .addComponent(cboArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtObra)
                            .addComponent(cboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValuacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAncho1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAncho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngreso)))
                    .addComponent(lblArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 280, 504));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValuacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValuacionKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo numeros");
        }
        if (txtValuacion.getText().length() > 9) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar hasta 10 caracteres");
        }
    }//GEN-LAST:event_txtValuacionKeyTyped

    private void txtObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObraActionPerformed

    }//GEN-LAST:event_txtObraActionPerformed

    private void txtObraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObraKeyTyped
        // TODO add your handling code here:

        char validar2 = evt.getKeyChar();
        if (Character.isDigit(validar2)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo Letras");
        }
    }//GEN-LAST:event_txtObraKeyTyped

    private void txtAltoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltoKeyTyped

        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo numeros");
        }
    }//GEN-LAST:event_txtAltoKeyTyped

    private void txtAnchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnchoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo numeros");
        }
    }//GEN-LAST:event_txtAnchoKeyTyped

    private void cargarCombo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        list = g.llenarCombo();

        for (Artista art : list) {
            model.addElement(art.getNombre());

        }
        cboArtista.setModel(model);
    }

    private int devolverid(String est) {
        int var = 0;
        for (Artista art : list) {
            if (art.getNombre().equals(est)) {
                var = art.getId_artista();
            }
        }
        return var;
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (!txtAlto.getText().equals("") && !txtAncho.getText().equals("") && !txtAlto.getText().equals("") && !txtValuacion.getText().equals("") && !txtValuacion.getText().equals("") && !txtObra.getText().equals("")) {

            int alto = Integer.parseInt(txtAlto.getText());
            int ancho = Integer.parseInt(txtAncho.getText());
            String ingreso = txtValuacion.getText();
            String nombreobra = txtObra.getText();
            int valuacion = Integer.parseInt(txtValuacion.getText());
            String descripcion = (String) cboDescripcion.getSelectedItem();

            String art = (String) cboArtista.getSelectedItem();
            int artista = devolverid(art);

            String gen = (String) cboGenero.getSelectedItem();

            Obra o = new Obra(artista, nombreobra, gen, valuacion, descripcion, alto, ancho, ingreso);

            g.RegistarObras(o);

            JOptionPane.showMessageDialog(this, "Obra Cargada Con Exito");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese Todos Los Campos");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setLocationRelativeTo(null);
        p.setDefaultCloseOperation(p.EXIT_ON_CLOSE);
        p.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int alto = Integer.parseInt(txtAlto.getText());
        int ancho = Integer.parseInt(txtAncho.getText());
        String ingreso = txtValuacion.getText();
        String nombreobra = txtObra.getText();
        int valuacion = Integer.parseInt(txtValuacion.getText());
        String descripcion = (String) cboDescripcion.getSelectedItem();

        String art = (String) cboArtista.getSelectedItem();
        int artista = devolverid(art);

        String gen = (String) cboGenero.getSelectedItem();

        Obra o = new Obra(listo.getId_obra(), artista, nombreobra, gen, valuacion, descripcion, alto, ancho, ingreso);

        g.ModificarObras(o);

        JOptionPane.showMessageDialog(this, "Obra Cargada Con Exito");

        abrir();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        ListaObras e = new ListaObras();

        e.setLocationRelativeTo(null);
        e.setDefaultCloseOperation(e.EXIT_ON_CLOSE);
        e.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void txtValuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValuacionActionPerformed

    private void txtIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingresar Solo numeros");
        }
    }//GEN-LAST:event_txtIngresoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarObraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarObraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarObraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarObraa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarObraa().setVisible(true);
            }
        });
    }

    private int idAModificar = -1; //Por defecto representa que se va a agregar una nueva persona


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JComboBox<String> cboArtista;
    private javax.swing.JComboBox<String> cboDescripcion;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JLabel lblAncho1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblValuacion;
    private javax.swing.JLabel phto;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtObra;
    private javax.swing.JTextField txtValuacion;
    // End of variables declaration//GEN-END:variables

    private void cargartxt() {
        String na = listo.getNombreartista();
        cboArtista.setSelectedItem(na);
        String ge = listo.getGenero();
        cboGenero.setSelectedItem(ge);
        String des = listo.getDescripcion();
        cboDescripcion.setSelectedItem(des);
        txtAlto.setText(String.valueOf(listo.getAlto()));
        txtAncho.setText(String.valueOf(listo.getAncho()));
        txtValuacion.setText(String.valueOf(listo.getIngreso()));
        txtObra.setText(listo.getNombre());
        txtValuacion.setText(String.valueOf(listo.getValuacion()));

    }

    private void abrir() {

        ListaObras o = new ListaObras();
        o.setVisible(true);
        o.setLocationRelativeTo(null);
        o.setDefaultCloseOperation(o.EXIT_ON_CLOSE);

        this.setVisible(false);
        this.dispose();

    }
}
