/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package museo;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Expocicion;
import model.GestorBD;
import model.Restauracion;

/**
 *
 * @author Usuario
 */
public class Restauraciones extends javax.swing.JFrame {

    GestorBD db = new GestorBD();
    int value = 0;
    int proceso = 0;

    /**
     * Creates new form Restauraciones
     */
    public Restauraciones() {
        initComponents();
        cargarlista();
      rbtSi.setVisible(false);
        ButtonGroup gb = new ButtonGroup();
        {
            gb.add(rbtNo);
            gb.add(rbtSi);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableres = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rbtSi = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        rbtNo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Harrington", 1, 32)); // NOI18N
        jLabel4.setText("Restauraciones");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        tableres.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        tableres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableres);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 640, 130));

        btnVolver.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        btneliminar.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar Restauracion seleccionada");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 300, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/brushes-2552433_640.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 640, 320));

        rbtSi.setBackground(new java.awt.Color(51, 51, 51));
        rbtSi.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        rbtSi.setForeground(new java.awt.Color(255, 255, 255));
        rbtSi.setText("si");
        jPanel1.add(rbtSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 40, -1));

        btnModificar.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        btnModificar.setText("Aceptar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 130, -1));

        rbtNo.setBackground(new java.awt.Color(51, 51, 51));
        rbtNo.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        rbtNo.setForeground(new java.awt.Color(255, 255, 255));
        rbtNo.setText("Si");
        jPanel1.add(rbtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 40, -1));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dar de alta obra restaurada");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        Principal p = new Principal();
        p.setLocationRelativeTo(null);
        p.setDefaultCloseOperation(p.EXIT_ON_CLOSE);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tableresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseClicked

        String v = "";
        int index = tableres.getSelectedRow();
        TableModel model = tableres.getModel();
        value = Integer.parseInt(model.getValueAt(index, 0).toString());

        v = db.versiono(value);

        if (v.equals("si")) {
            rbtNo.setSelected(false);
            rbtSi.setSelected(true);

            proceso = 1;

        } else {

            rbtNo.setSelected(true);
            rbtSi.setSelected(false);
            proceso = 0;
        }


    }//GEN-LAST:event_tableresMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String estado = "";
        if (rbtNo.isSelected()) {
            estado = "no";
            if (value > 0) {
                db.modificarRest(value);
                cargarlista();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione Una Obra");
            }
        }
        if (rbtSi.isSelected()) {
            estado = "si";
            JOptionPane.showMessageDialog(this, "Seleccione Para no Restaurar");
            return;
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        
        if (value > 0) {
            db.EliminarRest(value);
            JOptionPane.showMessageDialog(this, "Se Elimino con Exito");
            cargarlista();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione una Obra");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restauraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restauraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restauraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restauraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restauraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtNo;
    private javax.swing.JRadioButton rbtSi;
    private javax.swing.JTable tableres;
    // End of variables declaration//GEN-END:variables

    private void cargarlista() {
        ArrayList<Restauracion> lista = db.mostarResta();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = new DefaultTableModel();

        String[] titulos = new String[]{"Id", "restauracionObra", "restauracion", "nombreObra", "nombre", "apellido"};
        dtm.setColumnIdentifiers(titulos);
        tableres.setModel(dtm);
        // idGasto,descripcion,importe,nombre,maximoAutorizado
        for (Restauracion lg : lista) {
            Object[] row = {lg.getId(), lg.getRestauracionObra(), lg.getRestauracion(), lg.getNombreObra(), lg.getNombre(), lg.getApellido()};
            dtm.addRow(row);
        }
        tableres.setModel(dtm);
    }
}
